# tox -c tox-passagemath.ini
[tox]
envlist = passagemath

[testenv:passagemath]
usedevelop = True
extras = passagemath

setenv =
    # For access to _doctest_environment.py
    PYTHONPATH=.

commands =
    sage -tp --environment=sage.all__sagemath_modules dual_pairs
